package ubet:bos;

interface pipes {
    resource call-object;
    resource call-error;
    resource call-args {
        constructor(init: list<u8>);
    }
    type call-result = result<call-object, call-error>;

    resource step {
        take: func(step: step, call: call-object) -> call-result;
    } 
    resource steps {
        next: func() -> option<step>;
    }

    pipe: func(steps: steps, args: call-args) -> call-result;
}

world bos {
    export pipes; 
}
