package ubet:bos;

interface pipes {
    resource call-object;
    resource call-error;
    type call-result = result<call-object, call-error>;

    dispatch: func(env: list<tuple<string, string>>, binargs: list<u8>) -> call-result;
}

world bos {
    import wasi:clocks/monotonic-clock@0.2.6;
    export pipes; 
}
